In [1]:
import random
import gurobipy as gp
from gurobipy import GRB
import copy
import numpy as np

n=25
def generate_data(n):
    # Initializing an empty adjacency matrix with zeros
    W = [[0] * n for _ in range(n)]

    # Generate random edge weights (assuming non-negative weights)
    for i in range(n):
        for j in range(i+1, n):
            t = random.randint(0,2)
            if t == 0:
                weight = 0
            else:
                weight = random.randint(1,10)
            # weight = random.uniform(0, 2)  # Adjust the range as needed
            # Ensure that edges are undirected by setting W[i][j] = W[j][i] = weight
            W[i][j] = W[j][i] = weight
    return W

In [2]:
def BP(W,n):
    # Create a new model
    m = gp.Model("mip1")
    # Create variable

    x = {}
    x = m.addVars(range(n),vtype = "B", name="x")
    y = m.addVars(range(n),range(n),vtype = "B", name="y")

    m.setObjective(sum(W[i][j]*y[i,j] for i in range(n) for j in range(n)), GRB.MAXIMIZE)
    m.addConstrs(y[i,j]<=(x[i]+x[j]) for i in range(n) for j in range(n))
    m.addConstrs(y[i,j]+x[i]+x[j]<=2 for i in range(n) for j in range(n))
    m.optimize()
    y_result=[]

    for v in x.values():
        if v.X == 0 or v.X==-0:
            y_result.append(0)
        else:
            y_result.append(1)
    return y_result

In [3]:
def summing_W(W: list):
    sum_W = []
    for i in range(len(W)):
        value = sum(W[i])
        sum_W.append(value)
    temp_W = W.copy()
    temp_W.append(sum_W.copy())

    for i in range(len(temp_W)):
        if i==len(temp_W)-1:
            temp_W[i].insert(len(temp_W),0)
        else:
            temp_W[i].insert(len(temp_W),sum_W[i])
    return  sum_W, temp_W

In [4]:
def get_data(k):
    xdata1_l = []
    xdata2_l = []
    ydata1_l = []
    data_list = []
    outcome = []
    for i in range(k):
        data = generate_data(n)
        result = BP(data, n)
        raw_data = copy.deepcopy(data)
        sum_data, matrix_data = summing_W(data)
        xdata1_l.append(sum_data)
        xdata2_l.append(matrix_data)
        ydata1_l.append(result)
        #experimental
        for j in range(len(raw_data)):
        #     # data_list.append(sum(raw_data[j]))
        #     data_list.append(sum(raw_data[j]))
            outcome.append(result[j])
        for j in raw_data:
            j.append(sum(j))
            data_list.append(j)
    
    ydata2_l = copy.deepcopy(ydata1_l)
    for i in ydata2_l:
        i.append(-1)

    raw_data = np.array(data_list)
    raw_outcome = np.array(outcome)
    xdata1 = np.array(xdata1_l)
    xdata2 = np.array(xdata2_l)
    ydata1 = np.array(ydata1_l)
    ydata2 = np.array(ydata2_l)
    return xdata1, xdata2, ydata1, ydata2, raw_data, raw_outcome

In [5]:
t = [[1,3,4,5],
     [5,8,4,0]]
for i in t:
    i.append(sum(i))
# t2 = []
# for i in range(len(t)):
#     t2.append(sum(t[i]))
# t2
t

[[1, 3, 4, 5, 13], [5, 8, 4, 0, 17]]

In [6]:
k = 500
xtrain1, xtrain2, ytrain1, ytrain2, raw_data_train, raw_outcome_train = get_data(k)

k = 100
xtest1, xtest2, ytest1, ytest2, raw_data_test, raw_outcome_test = get_data(k)

Restricted license - for non-production use only - expires 2024-10-28
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 1250 rows, 650 columns and 3700 nonzeros
Model fingerprint: 0x2133b332
Variable types: 0 continuous, 650 integer (650 binary)
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [1e+00, 1e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e+00, 2e+00]
Found heuristic solution: objective -0.0000000
Presolve removed 828 rows and 414 columns
Presolve time: 0.02s
Presolved: 422 rows, 236 columns, 1266 nonzeros
Variable types: 0 continuous, 236 integer (236 binary)
Found heuristic solution: objective 764.0000000

Root relaxation: objective 2.314000e+03, 38 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bo

H    0     0                    1388.0000000 2148.00000  54.8%     -    0s
H    0     0                    1416.0000000 1714.02389  21.0%     -    0s
     0     0 1714.02389    0  221 1416.00000 1714.02389  21.0%     -    0s
     0     0 1624.56437    0  232 1416.00000 1624.56437  14.7%     -    0s
     0     0 1608.70728    0  235 1416.00000 1608.70728  13.6%     -    0s
     0     0 1606.33584    0  234 1416.00000 1606.33584  13.4%     -    0s
     0     0 1605.20376    0  236 1416.00000 1605.20376  13.4%     -    0s
     0     0 1604.37412    0  236 1416.00000 1604.37412  13.3%     -    0s
     0     0 1604.11252    0  236 1416.00000 1604.11252  13.3%     -    0s
H    0     0                    1442.0000000 1554.34841  7.79%     -    0s
     0     0 1554.34841    0  234 1442.00000 1554.34841  7.79%     -    0s
     0     0 1544.82206    0  235 1442.00000 1544.82206  7.13%     -    0s
     0     0 1543.85188    0  236 1442.00000 1543.85188  7.06%     -    0s
     0     0 1543.44063  

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score

def build_binary_model(xtrain, ytrain, xtest, ytest, nrlayers, nrnodes, rate, k):
    # This function builds the model with nrlayes layers and nrnodes nodes in each layer
    # nrlayers is a number and nrnodes is a vector specifying how many nodes each layer should contain
    model = keras.Sequential()
    numclasses = k

    # add the layers
    for i in range(nrlayers + 1):
        if (i == 0):
            # input layer
            model.add(keras.Input(shape=input_shape))
        else:
            # hidden layers
            nrnode = nrnodes[i - 1]
            model.add(keras.layers.Dense(nrnode, activation="sigmoid"))

    model.add(keras.layers.Dense(numclasses, activation="sigmoid"))

    # give summary of model
    model.summary()

    # train model
    batch_size = 30 # Based on SGD --> 1 gradient is calculated using 32 data points every time
    #so in each epoch, training_size/batch_size many gradient calculations and weight updates
    epochs = 10 # How many times to go through the data to complete the SGD

    opt = keras.optimizers.SGD(learning_rate=rate)
    model.compile(loss="binary_crossentropy",
                  optimizer=opt,
                  metrics=["accuracy"])
    
    # class AccuracyCallback(keras.callbacks.Callback):
    #     def on_epoch_end(self, epoch, logs=None):
    #         loss, accuracy = self.model.evaluate(xtrain, ytrain, verbose=0)
    #         print(f" Training accuracy for epoch {epoch + 1}: {accuracy:.4f} ")
            
    # fit the model, note that keras takes care of the train set/validation set
    # model.fit(xtrain, ytrain, batch_size=batch_size, epochs=epochs, validation_split=0.1, callbacks=[AccuracyCallback()])
    model.fit(xtrain, ytrain, batch_size=batch_size, epochs=epochs, validation_split=0.1,)
    score_train = model.evaluate(xtrain, ytrain, verbose=1)
    print(f"Train loss:, {score_train[0]}, Train accuracy:, {score_train[1]}")
    # get results
    score = model.evaluate(xtest, ytest, verbose=1)
    print(f"Test loss: {score[0]}, Test accuracy:, {score[1]}")
    return model

In [ ]:
# input_shape = (n+1, )
# models1 = build_binary_model(raw_data_train, raw_outcome_train, raw_data_test, raw_outcome_test, 4, [1000, 750, 250, 100], 0.02, 1)

In [ ]:
# print(xtrain1.shape)
# print(xtrain2.shape)
# print(ytrain1.shape)
# print(ytrain2.shape)
# print(xtest1.shape)
# print(xtest2.shape)
# print(ytest1.shape)
# print(ytest2.shape)

In [ ]:
input_shape = (n, )
models1 = build_binary_model(xtrain1, ytrain1, xtest1, ytest1, 1, [5], 0.02, n)


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 5)                 55        
                                                                 
 dense_23 (Dense)            (None, 10)                60        
                                                                 
Total params: 115 (460.00 Byte)
Trainable params: 115 (460.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
15/15 [==============================] - 1s 32ms/step - loss: 0.7220 - accuracy: 0.0022 - val_loss: 0.7134 - val_accuracy: 0.0000e+00
Epoch 2/10
15/15 [==============================] - 0s 15ms/step - loss: 0.7183 - accuracy: 0.0089 - val_loss: 0.7120 - val_accuracy: 0.0000e+00
Epoch 3/10
15/15 [==============================] - 0s 20ms/step - loss: 0.7157 - accuracy: 0.0156 - val_loss: 0.7108 - va

In [ ]:
import math

xtrain2=np.reshape(xtrain2,[500, int(math.pow(n+1,2))])
xtest2=np.reshape(xtest2,[100, int(math.pow(n+1,2))])

input_shape = (int(math.pow(n+1,2)), )
models2 = build_binary_model(xtrain2, ytrain2, xtest2, ytest2, 3, [100, 50, 20], 0.02, n+1)


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 100)               12200     
                                                                 
 dense_25 (Dense)            (None, 50)                5050      
                                                                 
 dense_26 (Dense)            (None, 20)                1020      
                                                                 
 dense_27 (Dense)            (None, 11)                231       
                                                                 
Total params: 18501 (72.27 KB)
Trainable params: 18501 (72.27 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
 1/15 [=>............................] - ETA: 10s - loss: 0.7675 - accuracy: 0.0000e+00

 Training accuracy for epoch 1: 0.0000 
15/15 [==============================] - 1s 33ms/step - loss: 0.7442 - accuracy: 0.0000e+00 - val_loss: 0.7163 - val_accuracy: 0.0000e+00
Epoch 2/10
15/15 [==============================] - 0s 11ms/step - loss: 0.6996 - accuracy: 0.0000e+00 - val_loss: 0.6741 - val_accuracy: 0.0000e+00
Epoch 3/10
15/15 [==============================] - 0s 10ms/step - loss: 0.6596 - accuracy: 0.0000e+00 - val_loss: 0.6360 - val_accuracy: 0.0000e+00
Epoch 4/10
15/15 [==============================] - 0s 10ms/step - loss: 0.6233 - accuracy: 0.0000e+00 - val_loss: 0.6012 - val_accuracy: 0.0000e+00
Epoch 5/10
15/15 [==============================] - 0s 10ms/step - loss: 0.5900 - accuracy: 0.0000e+00 - val_loss: 0.5692 - val_accuracy: 0.0000e+00
Epoch 6/10
15/15 [==============================] - 0s 11ms/step - loss: 0.5592 - accuracy: 0.0000e+00 - val_loss: 0.5394 - val_accuracy: 0.0000e+00
Epoch 7/10
15/15 [==============================] - 0s 10ms/step - loss: 0.53

In [ ]:
test1 = models1.predict(xtest1)[0]
print(models1.predict(xtest1)[0])

4/4 [==============================] - 0s 3ms/step
[0.5424986  0.59454155 0.42335203 0.5208736  0.4059182  0.54170597
 0.51725715 0.53107667 0.6337784  0.39273927]


In [ ]:
convert = []
for i in test1:
    if i>0.5:
        convert.append(1)
    else:
        convert.append(0)
print(np.array(convert))
print(ytest1[0])

[1 1 0 1 0 1 1 1 1 0]
[1 1 0 0 1 0 0 1 0 1]


In [ ]:
test2 = models2.predict(xtest2)[0]
print(models2.predict(xtest2)[0])

4/4 [==============================] - 0s 2ms/step
[0.5282917  0.3841067  0.40494847 0.5379432  0.38957217 0.5053684
 0.5261007  0.57099783 0.44749478 0.51512814 0.09102747]


In [ ]:
convert = []
for i in test2:
    if i>0.5:
        convert.append(1)
    else:
        convert.append(0)
print(np.array(convert))
print(ytest1[0])

[1 0 0 1 0 1 1 1 0 1 0]
[1 1 0 0 1 0 0 1 0 1]
